version: '3'

services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - 1883:1883
      - 10001:9001
    volumes:
      - ./mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=power_monitor
  power-monitor-parser:
    depends_on:
      - mqtt
    image: chajiuqqq/power-monitor-parser:dev
    environment:
      - BROKER_IP=mqtt
      - PORT=1883
      - PROFILE=dev
      - CRON=0 0 1 * * *
      - WX_TOKEN=Y5QLsGCwu2Qw2B
      - WX_RECEIVER_ID=ww35349f3d5dc5630e
      - WX_ENCODING_AES_KEY=SSVpwrcWZ0mKqOukYmtJoWgdpfM8Uhsp35XxRdykNvW
      - DB_HOST=mysql
      - DB_PASS=1234
      - DB=power_monitor

  power-monitor-api:
    depends_on:
      - mysql
    image: chajiuqqq/power-monitor-api:dev
    ports:
      - 1323:1323
    environment:
      - BROKER_IP=mqtt
      - PORT=1883
      - PROFILE=dev
      - CRON=0 0 1 * * *
      - WX_TOKEN=Y5QLsGCwu2Qw2B
      - WX_RECEIVER_ID=ww35349f3d5dc5630e
      - WX_ENCODING_AES_KEY=SSVpwrcWZ0mKqOukYmtJoWgdpfM8Uhsp35XxRdykNvW
      - DB_HOST=mysql
      - DB_PASS=1234
      - DB=power_monitor
