name: dev-image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Parser build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: cmd/parser/Dockerfile
          push: true
          tags: chajiuqqq/power-monitor-parser:dev

      - name: Api build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: cmd/api/Dockerfile
          push: true
          tags: chajiuqqq/power-monitor-api:dev