#name: Go Test
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  test:
#    name: Run Tests
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v2
#
#      - name: Set up Go
#        uses: actions/setup-go@v2
#        with:
#          go-version: 1.21
#
#      - name: Run tests
#        run: go test ./...
#        env:
#          BROKER_IP: 127.0.0.1
#          PORT: 1883
#          PROFILE: dev
#          CRON: "0 0 1 * * *"